name: menumaster
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.4+50

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  alphabet_list_view: ^0.1.10
  dio: ^5.3.2
  dotted_border: ^2.0.0+3
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  widgets_book:
    path: packages/widgets_book
  firebase_core: ^2.16.0
  firebase_dynamic_links: ^5.3.6
  firebase_analytics: ^10.4.5
  flutter_dotenv: ^5.1.0
  http: ^1.1.0
  js: ^0.6.7
  url_launcher: ^6.1.14
  webview_flutter: ^4.2.4
  emailjs: ^1.3.0

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.8

flutter:
  uses-material-design: true
  assets:
    - .env
  fonts:
    - family: Yugothic
      fonts:
        - asset: packages/widgets_book/assets/fonts/yugothib.ttf
        - asset: packages/widgets_book/assets/fonts/yugothic_bold.ttf
        - asset: packages/widgets_book/assets/fonts/yugothic_light.ttf
    - family: Poppins
      fonts:
        - asset: packages/widgets_book/assets/fonts/Poppins-Regular.ttf
        - asset: packages/widgets_book/assets/fonts/Poppins-Light.ttf
        - asset: packages/widgets_book/assets/fonts/Poppins-Medium.ttf
        - asset: packages/widgets_book/assets/fonts/Poppins-SemiBold.ttf
        - asset: packages/widgets_book/assets/fonts/Poppins-Bold.ttf