name: widgets_book
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  another_transformer_page_view: ^2.0.1
  bloc_test: ^9.1.4
  carousel_slider: ^4.2.1
  package_rename: ^1.5.0
  cloud_firestore: ^4.8.5
  connectivity_plus: ^5.0.2
  country: ^4.0.0
  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  firebase_auth: ^4.7.3
  firebase_core: ^2.16.0
  firebase_storage: ^11.2.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_credit_card: ^4.0.1
  flutter_dotenv: ^5.1.0
  flutter_gen: ^5.3.1
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.7
  fluttertoast: ^8.2.2
  flutter_form_builder: ^9.1.0
  form_builder_validators: ^9.0.0
  formz: ^0.6.0
  fpdart: ^1.1.0
  get_it: ^7.6.0
  go_router: ^12.1.1
  image_gallery_saver: ^2.0.3
  intl: ^0.18.1
  injectable: ^2.3.0
  json_annotation: ^4.8.1
  path: ^1.8.3
  path_provider: ^2.1.0
  retrofit: ^4.0.1
  scrollable_positioned_list: ^0.3.8
  screenshot: ^2.1.0
  shared_preferences: ^2.2.0
  shimmer: ^3.0.0
  url_launcher: ^6.1.12
  flutter_localization: ^0.1.13
  image_picker: ^1.0.2
  image_picker_platform_interface: ^2.9.0
  dotted_border: ^2.0.0+3
  step_progress_indicator: ^1.0.2
  uuid: ^4.2.1
  cached_network_image: ^3.3.0



dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^2.0.2
#  flutter_test:
#    sdk: flutter
  freezed: ^2.4.5
#  http_mock_adapter: ^0.5.0
  json_serializable: ^6.7.1
  mockito: ^5.4.2
  mocktail: ^1.0.0
  retrofit_generator: ^8.0.4
#  test: ^1.24.6
  very_good_analysis: ^5.0.0+1

dependency_overrides:
  analyzer: ^6.2.0
  freezed: 2.4.2
  test: ^1.24.6
  test_api: ^0.6.1


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Yugothic
      fonts:
        - asset: assets/fonts/yugothib.ttf
        - asset: assets/fonts/yugothic_bold.ttf
          weight: 700
        - asset: assets/fonts/yugothic_light.ttf
          weight: 300
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - weight: 400
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700


flutter_gen:
  output: lib/src/generated/
  line_length: 80

  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true


  integrations:
    flutter_svg: true
    package_parameter_enabled: true